/* Generated by build-scripts/gen_morphos_lib.py, do not edit. */
/* Jump table order: must match sdk/fd/sdl3_image_lib.fd */

#undef STUB
#undef STUB_STACK
#undef STUB_UNSUPPORTED

#if defined(GENERATE_STUBS)
/* r12 = library base: set this opener's r13, registers go through untouched */
#define STUB(name) extern int name(); int __saveds LIB_##name() { return name(); }
/* Same with arguments on the stack: a stub frame would hide them from the
   callee, so this one copies the caller's argument area (16 words) */
#define STUB_STACK(name) asm("\n\t.section \".text\"\n\t.align 2\n" \
	"\t.globl LIB_" #name "\n\t.type LIB_" #name ",@function\nLIB_" #name ":\n" \
	"\tstwu 1,-96(1)\n\tmflr 0\n\tstw 0,100(1)\n\tstw 13,88(1)\n" \
	"\tlwz 0,104(1)\n\tstw 0,8(1)\n" "\tlwz 0,108(1)\n\tstw 0,12(1)\n" "\tlwz 0,112(1)\n\tstw 0,16(1)\n" "\tlwz 0,116(1)\n\tstw 0,20(1)\n" "\tlwz 0,120(1)\n\tstw 0,24(1)\n" "\tlwz 0,124(1)\n\tstw 0,28(1)\n" "\tlwz 0,128(1)\n\tstw 0,32(1)\n" "\tlwz 0,132(1)\n\tstw 0,36(1)\n" "\tlwz 0,136(1)\n\tstw 0,40(1)\n" "\tlwz 0,140(1)\n\tstw 0,44(1)\n" "\tlwz 0,144(1)\n\tstw 0,48(1)\n" "\tlwz 0,148(1)\n\tstw 0,52(1)\n" "\tlwz 0,152(1)\n\tstw 0,56(1)\n" "\tlwz 0,156(1)\n\tstw 0,60(1)\n" "\tlwz 0,160(1)\n\tstw 0,64(1)\n" "\tlwz 0,164(1)\n\tstw 0,68(1)\n" \
	"\tlwz 13,36(12)\n\tbl " #name "\n" \
	"\tlwz 0,100(1)\n\tlwz 13,88(1)\n\taddi 1,1,96\n\tmtlr 0\n\tblr\n" \
	"\t.size LIB_" #name ",.-LIB_" #name "\n");
#define STUB_UNSUPPORTED(name)
#elif defined(GENERATE_POINTERS)
#define STUB(name) (APTR)&LIB_##name,
#define STUB_STACK(name) (APTR)&LIB_##name,
#define STUB_UNSUPPORTED(name) (APTR)&LIB_Unsupported,
#else
#define STUB(name) extern int LIB_##name();
#define STUB_STACK(name) extern int LIB_##name();
#define STUB_UNSUPPORTED(name)
#endif

	STUB(IMG_FreeAnimation)
	STUB(IMG_Version)
	STUB(IMG_Load)
	STUB(IMG_LoadAVIF_IO)
	STUB(IMG_LoadAnimation)
	STUB(IMG_LoadAnimationTyped_IO)
	STUB(IMG_LoadAnimation_IO)
	STUB(IMG_LoadBMP_IO)
	STUB(IMG_LoadCUR_IO)
	STUB(IMG_LoadGIFAnimation_IO)
	STUB(IMG_LoadGIF_IO)
	STUB(IMG_LoadICO_IO)
	STUB(IMG_LoadJPG_IO)
	STUB(IMG_LoadJXL_IO)
	STUB(IMG_LoadLBM_IO)
	STUB(IMG_LoadPCX_IO)
	STUB(IMG_LoadPNG_IO)
	STUB(IMG_LoadPNM_IO)
	STUB(IMG_LoadQOI_IO)
	STUB(IMG_LoadSVG_IO)
	STUB(IMG_LoadSizedSVG_IO)
	STUB(IMG_LoadTGA_IO)
	STUB(IMG_LoadTIF_IO)
	STUB(IMG_LoadTexture)
	STUB(IMG_LoadTextureTyped_IO)
	STUB(IMG_LoadTexture_IO)
	STUB(IMG_LoadTyped_IO)
	STUB(IMG_LoadWEBPAnimation_IO)
	STUB(IMG_LoadWEBP_IO)
	STUB(IMG_LoadXCF_IO)
	STUB(IMG_LoadXPM_IO)
	STUB(IMG_LoadXV_IO)
	STUB(IMG_Load_IO)
	STUB(IMG_ReadXPMFromArray)
	STUB(IMG_ReadXPMFromArrayToRGB888)
	STUB(IMG_SaveJPG)
	STUB(IMG_SaveJPG_IO)
	STUB(IMG_SavePNG)
	STUB(IMG_SavePNG_IO)
	STUB(IMG_SaveAVIF)
	STUB(IMG_SaveAVIF_IO)
	STUB(IMG_isAVIF)
	STUB(IMG_isBMP)
	STUB(IMG_isCUR)
	STUB(IMG_isGIF)
	STUB(IMG_isICO)
	STUB(IMG_isJPG)
	STUB(IMG_isJXL)
	STUB(IMG_isLBM)
	STUB(IMG_isPCX)
	STUB(IMG_isPNG)
	STUB(IMG_isPNM)
	STUB(IMG_isQOI)
	STUB(IMG_isSVG)
	STUB(IMG_isTIF)
	STUB(IMG_isWEBP)
	STUB(IMG_isXCF)
	STUB(IMG_isXPM)
	STUB(IMG_isXV)
	STUB(IMG_isANI)
	STUB(IMG_SaveTGA)
	STUB(IMG_SaveTGA_IO)
	STUB(IMG_SaveGIF)
	STUB(IMG_SaveGIF_IO)
	STUB(IMG_SaveWEBP)
	STUB(IMG_SaveWEBP_IO)
	STUB(IMG_SaveBMP)
	STUB(IMG_SaveBMP_IO)
	STUB(IMG_Save)
	STUB(IMG_SaveTyped_IO)
	STUB(IMG_CreateAnimationEncoder)
	STUB(IMG_CreateAnimationEncoder_IO)
	STUB(IMG_CreateAnimationEncoderWithProperties)
	STUB(IMG_AddAnimationEncoderFrame)
	STUB(IMG_CloseAnimationEncoder)
	STUB(IMG_LoadANIAnimation_IO)
	STUB(IMG_LoadAPNGAnimation_IO)
	STUB(IMG_LoadAVIFAnimation_IO)
	STUB(IMG_CreateAnimationDecoder)
	STUB(IMG_CreateAnimationDecoder_IO)
	STUB(IMG_CreateAnimationDecoderWithProperties)
	STUB(IMG_GetAnimationDecoderFrame)
	STUB(IMG_ResetAnimationDecoder)
	STUB(IMG_CloseAnimationDecoder)
	STUB(IMG_GetAnimationDecoderProperties)
	STUB(IMG_GetAnimationDecoderStatus)
	STUB(IMG_GetClipboardImage)
	STUB(IMG_CreateAnimatedCursor)
	STUB(IMG_SaveCUR)
	STUB(IMG_SaveCUR_IO)
	STUB(IMG_SaveICO)
	STUB(IMG_SaveICO_IO)
	STUB(IMG_SaveAnimation)
	STUB(IMG_SaveAnimationTyped_IO)
	STUB(IMG_SaveANIAnimation_IO)
	STUB(IMG_SaveAPNGAnimation_IO)
	STUB(IMG_SaveAVIFAnimation_IO)
	STUB(IMG_SaveGIFAnimation_IO)
	STUB(IMG_SaveWEBPAnimation_IO)
	STUB(IMG_LoadGPUTexture)
	STUB(IMG_LoadGPUTexture_IO)
	STUB(IMG_LoadGPUTextureTyped_IO)
